[package]
name = "twitch-chat-rs"
version = "0.1.0"
authors = ["Innectic <innectic@gmail.com>"]

[dependencies]
reqwest = "0.8.8"
maplit = "1.0.1"
ws = { version = "0.7.8", features = ["ssl"] }
env_logger = "0.5.13"
url = "1.7.0"
